Repository sidharrth2002/sambal-sos-app, pull requests merged in 2021-07, with the labels that each got.

#15 [Chore] Added workflows script to automate updating foodbanks at 8am MYT daily
  .github/update-workflows.yml
  update_foodbanks.py
Labels: enhancement

#23 Improved script reliability + added lat/lng parsing
  update_foodbanks.py
Labels: bug, enhancement

#29 Feat/facebook login
  package-lock.json
  package.json
  src/assets/index.js
  src/assets/svgs/facebook.svg
  src/assets/svgs/google-login.svg
  src/screens/Auth/index.js
Labels: enhancement, feat

#84 Fix - configure GitHub action to check out from production instead of main
  .github/workflows/update-workflows.yml
Labels: bug

#86 Missing Translations, Updated Workflow Made Live
  .github/workflows/update-workflows.yml
  README.md
  contributing.md
  publicity.md
  src/components/LanguageSwitcher/index.js
  src/i18n.js
  src/screens/Auth/index.js
  src/screens/ReportForm/index.js
  src/translations/cn/translations.json
  src/translations/en/translations.json
  src/translations/malay/translations.json
Labels: new-release

#90 Fix Squeezed Images In Modal Made Live
  src/screens/Home/index.js
Labels: new-release
